"""
Django settings for tto project.

Generated by 'django-admin startproject' using Django 1.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qn2!@da6f!$j+ed+++^ft&oehs9ox_8kmpp*@90i*%3d3t@8@-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'TTO.apps.TtoConfig',
    'posts','users',
    'rest_framework']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/



SITE_ROOT = os.path.dirname(os.path.realpath(__file__))

STATICFILES_DIRS = [
  os.path.join(BASE_DIR, 'static/'),
]
STATIC_URL = '/static/'

MEDIA_URL="/media/"
MEDIA_ROOT=os.path.join(BASE_DIR,"media/")

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}

"""
curl -X POST -d "username=ozanteoman&password=yusuf541" http://127.0.0.1:8000/api/auth/token/

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlb21hbkBjYXJwZWR1LmNvbSIsInVzZXJuYW1lIjoib3phbnRlb21hbiIsInVzZXJfaWQiOjEsImV4cCI6MTUxMzQxOTcxMn0.NuHkuk9ja62CRU8oWFX1PL1cFnJKFrkofp98Q0d1hUs

$ curl -H "Authorization: JWT <your_token>" http://localhost:8000/protected-url/

curl -H "Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRlb21hbkBjYXJwZWR1LmNvbSIsInVzZXJuYW1lIjoib3phbnRlb21hbiIsImV4cCI6MTUxMzQyMjE2Mn0.tN0RJvCD-aYiLdzQ_L1WJB53OSiIU9uaL12w6EJbBe8" http://127.0.0.1:8000/posts-apiV1/comments/

curl -H "Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MTM0MjEyNjEsInVzZXJfaWQiOjEsInVzZXJuYW1lIjoib3phbnRlb21hbiIsImVtYWlsIjoidGVvbWFuQGNhcnBlZHUuY29tIn0.GKvTrfcb02JBxAjBZX7Oq1ZgB_GJ8zVol4MjF6SY2TM" http://localhost:8000/posts-apiV1/comments/

curl -H "Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6InRlb21hbkBjYXJwZWR1LmNvbSIsInVzZXJuYW1lIjoib3phbnRlb21hbiIsImV4cCI6MTUxMzQyMjE2Mn0.tN0RJvCD-aYiLdzQ_L1WJB53OSiIU9uaL12w6EJbBe8" -X POST -d "content=hello this is content&post=11" http://localhost:8000/posts-apiV1/comments-create/
curl -H "Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im96YW50ZW9tYW4iLCJ1c2VyX2lkIjoxLCJleHAiOjE1MTM0MjI2MjcsImVtYWlsIjoidGVvbWFuQGNhcnBlZHUuY29tIn0.iMgn0IcOUy6mkTgnH9FdTItG_9bne8wMugWauJpGvM0" -X POST -d "title=selam&content=hello this is content" http://localhost:8000/posts-apiV1/posts/create/


"""